apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d0k1502fc-nodejs
  janus-idp.io/tekton: d0k1502fc-nodejs
  backstage.io/kubernetes-id: d0k1502fc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0k1502fc-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
